### ISSUE TITLE
Define process to handle TextClass administrative metadata? Like, what collections and groups an item was in in DLXS?

### ISSUE THREAD

**Issue by njaffer** [mlibrary/objectclass#7]
collections now, groups later
- [x] identify metadata available in the debug=xml view
- [x] design metadata xml block and store in admSec

**Comment by respinos** [comment]
TODO: what _are_ groups? Are groups functionally just a collection? What about when groups are used to impose branding on its collections?

**Comment by jweise** [comment]
Is it ever the case that the group becomes the collection and collection goes away? 

We need to understand that Publishing with Groups. 

e.g. if TCP items knew their access restrictions, then the group would become the collection.EEBO grouop would become the EEBO collection, and collections would blend together (eebo1, eebo2, because we would have true item level auth). 

Just knowing what colllections and groups an item was in would allow us to say "if group=x do this" for example. e.g. any of the collections that begin "acls" should not be a single collection.

**Comment by cmkpowell** [comment]
Although the ticket separates collections and groups, I treating both at once. The real question here is do we want to make a collection METS for collection level information, like auth settings and stakeholder contact info.
